### ISSUE TITLE
Warning: Address of local variable returned

### ISSUE THREAD

**Issue by RaisinTen** [DSC-KIIT/project-halide#20]
I get this warning when compiling [`utils.cpp`](https://github.com/DSC-KIIT/project-halide/blob/master/src/utils.cpp):

![](https://user-images.githubusercontent.com/42526976/94267898-fc66f700-ff59-11ea-8f55-acf2454fbc8d.png)

I think not getting rid of this might later lead to serious problems because you never know when the memory will get out of access.

Probably this is the right way:
* dynamically allocate the memory by using `malloc` _(i know `malloc` = bad but I'm open to better suggestions)_
* `free` it when it has no use anymore

**Comment by junaidrahim** [comment]
Yeah, the thing is that as we are writing the kernel, we do not have the C/C++ standard library features we get along with our operating systems. So we cannot use the `free` and `malloc` functions.

We can use `new` and `delete` though as they are keywords and part of the language.

You can read up about this [here](https://wiki.osdev.org/How_kernel,_compiler,_and_C_library_work_together)

**Comment by RaisinTen** [comment]
Oh, right! In that case, we can't use `new` or `delete` either because `operator new` and `operator delete` are defined in `libstdc++.so`. I changed `util.cpp` into this:
```cpp
#include <utils.h>

void *mem_alloc(int nbytes) {
    return static_cast<void*>(new char[nbytes]);
}
```
and this is what happens when I try to link it:
```sh
utils.o: In function `mem_alloc(int)':
utils.cpp:(.text+0x1b): undefined reference to `operator new[](unsigned int)'
Makefile:20: recipe for target 'kernel.bin' failed
```
So, as mentioned in the article, since the kernel is supposed to deal with the memory management, I think this function should be some sort of an entry point for our version of a `malloc` or a `new`.

**Comment by junaidrahim** [comment]
oh shoot
yeah, you're right. `new` and `delete` don't work either.

I think this "hack" of returning a local variable will go away when we implement a proper memory management system.
