### ISSUE TITLE
Refactoring: replace all ifndef wrappers with #pragma once

### ISSUE THREAD

**Issue by RaisinTen** [DSC-KIIT/project-halide#23]
This:
```sh
git grep \#ifndef
```
produced these:
![](https://user-images.githubusercontent.com/42526976/94273860-9894fc00-ff62-11ea-991f-956bf17af0b1.png)

Because of [this](https://stackoverflow.com/a/1143958) maybe we should replace all of them with these:
```cpp
#pragma once
```

**Comment by junaidrahim** [comment]
@Ujjwal-Shekhawat please review this
